### ISSUE TITLE
ネットワークが低速な時に名前だけ切り替わって画像が前の人が表示されてしまう問題

### ISSUE THREAD

**Issue by yayoimizuha** [emolga587/hpsort2#4]
ローディングのぐるぐるをつける

**Comment by emolga587** [comment]
ローディングのスピナーを実装するのは効果の割に大変なので優先度低めで。画像の軽量化・キャッシュ保持期間を長めにするなどの対応でとりあえずはしのぎます

**Comment by yayoimizuha** [comment]
大変であれば画像をクリアしてまっさらにするのでもありかもしれません(こっちでもいろいろやってみます)

**Comment by yayoimizuha** [comment]
WebP化しますか？
